<?php

namespace AppBundle\Repository;

/**
 * agentStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agentStateRepository extends \Doctrine\ORM\EntityRepository
{
}
