<?php

namespace AppBundle\Repository;

/**
 * agentSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agentSessionRepository extends \Doctrine\ORM\EntityRepository
{    
   
    
    /* por ahora inutilizada, utlizare para rastrear sessiones abiertas*/
    public function findOpenSessions(){
        
        $qb = $this->createQueryBuilder('s');
        
        $qb->where('s.logout is NULL')
          ;
        
        return $qb->getQuery()->getResult();
    }
}
