<?php

namespace AppBundle\Repository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agentRepository extends \Doctrine\ORM\EntityRepository
{
}
