<?php

namespace AppBundle\Repository;

/**
 * positionStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class positionStateRepository extends \Doctrine\ORM\EntityRepository
{
}
