<?php

namespace AppBundle\Repository;

/**
 * turnStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class turnStateRepository extends \Doctrine\ORM\EntityRepository
{
}
