<?php

namespace AppBundle\Repository;

/**
 * turnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class turnRepository extends \Doctrine\ORM\EntityRepository {

        public function findToWaitingRoom(\DateTime $date) {

        $qb = $this->createQueryBuilder('t');
        $qb
                ->leftJoin('t.line', 'l')
                ->leftJoin('t.state', 's')
                ->where($qb->expr()->in('s.id', [1,2]))
                ->andWhere($qb->expr()->eq('t.date', $date->format("'Y-m-d'")))
          ;

        return $qb->getQuery()->getResult();
    }

}
