<?php

namespace AppBundle\Repository;

/**
 * turnerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class turnTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
